services:
  reservations:
    build: 
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev resevations
    tty: true
    ports:
      - 46521:3000
    volumes:
      - ./:/app
      - /app/node_modules
  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    tty: true
    ports:
      - 46522:3000
    volumes:
      - ./:/app
      - /app/node_modules
  mongo:
    image: mongo
    ports:
      - 46520:27017