services:
  reservations:
    build: 
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn run start:dev reservations
    tty: true
    env_file:
      - ./apps/reservations/.env
    ports:
      - "46521:3000"
    volumes:
      - ./:/app
      - /app/node_modules
  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn run start:dev auth
    tty: true
    env_file:
      - ./apps/auth/.env
    ports:
      - "46522:3000"
    volumes:
      - ./:/app
      - /app/node_modules
  payments:
    build: 
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: yarn run start:dev payments
    tty: true
    env_file:
      - ./apps/payments/.env
    ports:
      - "46523:3000"
    volumes:
      - ./:/app
      - /app/node_modules
  mongo:
    image: mongo
    ports:
      - "46520:27017"